package com.android.haozi.wanandroid.bean

class ArticleDataBean(apkLink: String?,
                      author: String?,
                      chapterId: Int = -1,
                      chapterName: String?,
                      collect: Boolean = false,
                      courseId: Int = -1,
                      desc: String?,
                      envelopePic: String?,
                      fresh: Boolean = false,
                      id: Int = -1,
                      link: String?,
                      niceDate: String?,
                      origin: Any?,
                      prefix: Any?,
                      projectLink: String?,
                      publishTime: Long = -1,
                      superChapterId: Int = -1,
                      superChapterName: String?,
                      tags: Any?,
                      title: String?,
                      type: Int = -1,
                      userId: Int = -1,
                      visible: Int = -1,
                      zan: Int = -1)