package com.android.haozi.wanandroid.bean

class ArticleDataBean(var apkLink: String?,
                      var author: String?,
                      var chapterId: Int = -1,
                      var chapterName: String?,
                      var collect: Boolean = false,
                      var courseId: Int = -1,
                      var desc: String?,
                      var envelopePic: String?,
                      var fresh: Boolean = false,
                      var id: Int = -1,
                      var link: String?,
                      var niceDate: String?,
                      var origin: Any?,
                      var prefix: Any?,
                      var projectLink: String?,
                      var publishTime: Long = -1,
                      var superChapterId: Int = -1,
                      var superChapterName: String?,
                      var tags: Any?,
                      var title: String?,
                      var type: Int = -1,
                      var userId: Int = -1,
                      var visible: Int = -1,
                      var zan: Int = -1,
                      var hasHearted: Boolean = false)